# Generated by Django 5.2.4 on 2025-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'unique_together': {('coin', 'timestamp')},
            },
        ),
    ]
